### ISSUE TITLE
Add list of tables and list of figures

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-extensions-lab#111]
In many documents it is needed to have list of figures and list of tables right below table of contents. Would be good to have this feature in asciidoctor-pdf

**Comment by mojavelinux** [comment]
> This can be done using :sectnums!: asciidoctor.org/docs/user-manual/#numbering

If you're working at the API level, you can also set the `numbered` property on the section to false.

**Comment by lurch** [comment]
**OffTopic**:

> I think this issue needs to be moved to the extensions lab.

Seems as though transferring the issue to a different repo unsubscribed me from notifications, even though I'd previously commented on this issue :frowning_face: 
So for the benefit of other commenters on this issue who may want to re-subscribe to notifications...
ping @igagis @GeniusWaxer @GeekMustHave @1marc1 @znerd @UraniumKnight @Buzzardo @schulle877 


**OnTopic**:

I don't know Ruby, and @GeniusWaxer 's solution didn't _quite_ work for me as I have `:xrefstyle: short` enabled, so I've written a Python script which scans my source adoc for lines like:
```
.Caption for this table
[#tab-id_for_this_table]
```
and then writes
```
<<tab-id_for_this_table>> . . . . <<tab-id_for_this_table, Caption for this table>> +
```
into `list_of_tables.adoc` which I then `include::` into my main adoc.
Bit of an ugly solution, but it works for now :wink:

**Comment by twdrabek** [comment]
Couple of things.  First, this discussion is a loop, as in this thread links to another thread that links back to here.  Second, why has this not been implemented yet? It has been over 5 years.  Asciidoctor is referred to as the "Phd of markup", which is ironic due to the fact that scientific reports, theses, or dissertations require list of figures, tables, or listings.   Furthermore, this should be a standard feature--like a TOC--not an extension.

Perhaps it would be easier to just allow latex tags to pass through and execute during conversion of the document.  Asciidoctor's passthrough is nothing more than _ignore_.

Anyway, has anyone--in the past 5 years--found a way to create a consistent, professional document containing a list of tables and list of figures with page numbers.  Just for transparency, the LOT and LOF appear exactly as the TOC?

**Comment by mojavelinux** [comment]
> Second, why has this not been implemented yet? It has been over 5 years.

Because this is open source, I'm busy, and I don't work for you. That kind of attitude isn't going to get you anywhere in this community, so please take it somewhere else.

**Comment by twdrabek** [comment]
Thank you for the quick reply.  No, you don't work for me and I am sure you are busy--so am I.  People don't stumble around the internet and fall in this hole if they don't have an immediate problem to solve.  Therefore, "you can write it yourself" is not a legitimate answer--or argument against Word (just a click of the mouse).  I have enjoyed Asciidoctor for a couple of years now and it has saved me an immeasurable amount of time.  However, your attitude here shows me, and anyone else who happens to find this post, you work for yourself--not the community of the project.  It is unfortunate that Asciidoctor has hit such a plateau and is unable to perform in higher level documents.  I have re-tooled my workflow and moved to Emacs.  While there is a learning curve I am achieving my desired results.  Good luck with Asciidoctor.

**Comment by mojavelinux** [comment]
@twdrabek Good riddance. We don't need this kind of attitude in this community. It's simply not welcome.

**Comment by Alwinator** [comment]
I have added a "list of figures" extension (see [PR](https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/111)), time-wise and knowledge-wise I didn't managed to implement links, but it is a first step :)

**Comment by mojavelinux** [comment]
I would encourage you to create a separate repository and publish the code there. This repository has gotten completely out of hand. It was meant only to be a lab to show how extensions can be used. It's not meant to be the source of extensions for this project. I don't plan to merge additional PRs into this repository for full-fledged features.

**Comment by Alwinator** [comment]
No problem :)
You can find my new extension here: https://github.com/Alwinator/asciidoctor-lists

**Comment by mojavelinux** [comment]
Fantastic! And nice work!

**Comment by Alwinator** [comment]
Thanks! :)

**Comment by Alwinator** [comment]
@Buzzardo I have added a feature to [asciidoctor-lists](https://github.com/Alwinator/asciidoctor-lists) which allows lists of code snippets! I hope you like it.

**Comment by Alwinator** [comment]
@mojavelinux That would be great! I already have an account. In which stream/channel should I share my news?

**Comment by Mogztter** [comment]
@Alwinator you can use the "contrib releases" topic in the #annouce stream: https://asciidoctor.zulipchat.com/#narrow/stream/279652-announce.C2.A0.F0.9F.93.A2/topic/contrib.20releases

**Comment by bai-yi-bai** [comment]
Hello,
To fully adopt AsciiDoctor/AsciiDoctor-PDF, I need an LoF and LoT which has the same look-and-feel as the ToC. Since I am only a low-level Ruby programmer, I found and funded a developer off Fiverr.com to take the existing ToC generator in AsciiDoctor-PDF's converter.rb and modify it to produce a LoF. From the beginning, my intention was to open source this code and give it to the AsciiDoctor community to carry across the finish line. (I don't know how to package this into an extension, nor do I intend to).

I can discuss this further on the https://asciidoctor.zulipchat.com, or wherever is appropriate.

I have posted the .rb file to my personal github here:
[https://github.com/bai-yi-bai/asciidoctor-pdf-list-of-figures/blob/main/LoF/lof_extension_render_like_toc.rb](https://github.com/bai-yi-bai/asciidoctor-pdf-list-of-figures/blob/main/LoF/lof_extension_render_like_toc.rb)

Copying from the notes I posted in the file:
```
This LoF has these features:

- Provides a similar look-and-feel to the existing built-in ToC (it was built upon it).
- The page number is displayed.

Known issues:

- The Figure signifier, "Figure" is not printed.
- The Figure counter, "Figure 1" is not printed.
- The ability to add whitespace between the signifier, counter, and title would be nice
- This extension only works with a specific Figure title syntax. It is unclear what syntax this is. 
```

Following-up on the syntax issue. I provided the developer some test files which did not print the page number, it printed "?" with this:

```
image::image_file.ext[title='Title']
```

Through testing, I found that this syntax worked:

```
[[Title, Title]]
image::image_file.ext[title='Title']
```

I'm still not sure what the correct syntax for referencing a figure is (including the figure signifier, caption/title, or page number) perhaps this is a discussion better suited to the zulipchat.

I hope that a similar approach can be used to generate a List of Tables, and List of Examples. I'm not sure if 'hooking in' to the ToC generator will work... not all documents will include an LoT, an LoF, and an LoE.

**Comment by mojavelinux** [comment]
Since this became a community extension, I'm going to close this issue as there is no reason to duplicate it here.

See https://github.com/Alwinator/asciidoctor-lists

**Comment by bai-yi-bai** [comment]
A solution is now available: [https://gitlab.com/baiyibai/asciidoctor-pdf-lofte](https://gitlab.com/baiyibai/asciidoctor-pdf-loftel)

**Comment by RobertLbebber** [comment]
> Since this became a community extension, I'm going to close this issue as there is no reason to duplicate it here.
> 
> See https://github.com/Alwinator/asciidoctor-lists

This doesn't appear to be a valid solution on the merits that (from what I can tell) its doesn't list page numbers, so in that respects its not a table of Figures and Tables, but a List of Figures and Tables

**Comment by mojavelinux** [comment]
Please report your concern with that project.
