### ISSUE TITLE
Create lint extension

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-extensions-lab#6]
That way writers could ensure that theirs documents respect conventions and best practices. @mojavelinux  I'm sure you already have a list of best practices ? :smile:

Then it would be great to let users configure rules with a simple config file.

**Comment by sanmai-NL** [comment]
I'm quite interested in this as well. A range of conventions could be checked. The conventions that are useful to check range from requiring simple up to technically difficult checks. E.g. checking whether the rendering of document happens with certain attributes set would be less difficult than finding incorrectly marked up hyperlinks. Finding unavailable hyperlinks would be easier than finding suboptimal heading structure.

Since documentation is normally part of software release engineering process and should meet the concomitant QA criteria, it is natural to automatically run linters in addition to code linters.

**Comment by sanmai-NL** [comment]
@mojavelinux: what would be the way to go about programming such a linter. Would it best use an [extension point](http://asciidoctor.org/docs/user-manual/#extension-points)?

**Comment by mojavelinux** [comment]
@sanmai-NL Very likely a hybrid approach will be needed. To check the content, such as broken links, I might parse the document to the AST and examine it from there (a treeprocessor). Since inline parsing occurs during conversion, it might be necessary to look at the final output (a postprocessor). To check syntax, we're likely going to need to look at the raw text (a preprocessor). However, the preprocessor is tricky since it isn't aware of the document structure and lacks a lot of context.

So it really depends on what you want to focus on. My recommendation is to set some goals and then to try to find ways to accomplish those goals. Little by little, we'll have a linter framework.

**Comment by mojavelinux** [comment]
I've started work on a plugin for textlint so we can leverage the ecosystem already available. It just requires creating a new parser for AsciiDoc that can be hooked into that framework. You can find an early prototype here: https://github.com/opendevise/textlint-plugin-asciidoc This will converege with the work @Mogztter has been doing on a new inline parser for AsciiDoc at https://github.com/Mogztter/asciidoctor-inline-parser. It's still early days, but things are starting to move.

**Comment by mojavelinux** [comment]
As I have stated elsewhere, after doing some analysis, I came to realize that it's not feasible or even sensible for the parser that handles conversion also provide a framework for validation. These are very different concerns and should be handled with discrete tools. The reason is, a validator needs to know stuff about the document that the converter doesn't care about. And it needs to seek for things that the converter doesn't need or want to look for. So the validator would make the converter do a lot of extra work just for the purpose of validation. And the opposite is true as well. It's better that these tools evolve independently.

**Comment by sanmai-NL** [comment]
Checking can be done on the concrete syntax tree, whereas you are talking about the abstract syntax tree. Is there a grammar for Asciidoc(tor)? The linting tool can be implemented separately. Also, a more general linting tool could be made to operate on the HTML representation of technical documents.

**Comment by mojavelinux** [comment]
> Checking can be done on the concrete syntax tree, whereas you are talking about the abstract syntax tree.

Because that's where I think it needs to be checked to be any good.

> The linting tool can be implemented separately.

Exactly what I'm saying. But it will still need a parser implementation, which is what the textlint extension is for.

> Is there a grammar for Asciidoc(tor)? 

Not yet. The effort is picking up momentum though.

> a more general linting tool could be made to operate on the HTML representation of technical documents.

Such tools already exist. See [vale](https://github.com/errata-ai/vale) for one example. The problem I have with that approach is that there's no visibility into where the problem stems from in the AsciiDoc source, so it doesn't scale to large documentation sets.

**Comment by silopolis** [comment]
A tool like markdownlint would be awesome !

**Comment by mojavelinux** [comment]
A lint extension is not feasible. It needs to be a separate parser. The Asciidoctor parser is focused on parsing a valid AsciiDoc document and therefore doesn't capture all the information needed for a linter. I have linked to prototypes above. We could focus on developing those further, though they have a dependency on the AsciiDoc Language project producing a formal grammar on which that parsing can be based...and that work is still in progress.
